services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/postgresql/data
    # ports: ["5432:5432"]

  app:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.prod
    restart: always
    env_file:
      - .env.prod
    ports: ["3000:3000"]
    depends_on:
      - db

volumes:
  db_data:
