services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: offkai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  app:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.prod
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5432/offkai
    ports: ["3000:3000"]
    depends_on:
      - db

volumes:
  db_data:
